/*
 * Steps block
 * Numbered how-to steps. Step numbering and connector arrows are generated by
 * the block (CSS) so authors only supply each step's content (optional icon +
 * heading + body). Authored as a cards-style table: one row per step.
 */
export default function init(block) {
  const ul = document.createElement('ul');
  [...block.children].forEach((row) => {
    const li = document.createElement('li');
    li.className = 'steps-item';
    while (row.firstElementChild) li.append(row.firstElementChild);
    [...li.children].forEach((div) => {
      if (div.children.length === 1 && div.querySelector('picture')) div.className = 'steps-item-image';
      else div.className = 'steps-item-body';
    });
    ul.append(li);
  });
  block.textContent = '';
  block.append(ul);
}
